### PR TITLE
Add cover image, level adjust

### PR DESCRIPTION
**Pull request by dajare**
Seemed like a prime candidate for a level adjustment, especially in light of the book's title.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks!

**Comment by dajare** [comment]
@acabal - Two quick items by way of follow-up: (1) I've noticed quite a few covers that could benefit from this kind of tweaking, so I wrote up a "[How to enhance dull cover images](https://www.sudalyph.org/seci/how-to-enhance-dull-cover-images.html)" guide. I could add that as a PR to our "How-to" pages, if that would be welcome?

There's room for improving it, I expect, but hopefully it's a reasonable starting point.

(2) Would you also welcome PRs for existing covers (just the most affected examples) from the current corpus? I could whittle away at those.

I know you'll feel free to turn down either of these suggestions! :wink:

**Comment by acabal** [comment]
Maybe, but much of this is a matter of taste. What other covers are you looking at?

**Comment by dajare** [comment]
True about a matter of "taste"! Here are just six by way of example, each of which would benefit from a "cleaning", as it were:

- [The Golden Ass, by Apuleius. Translated by William Adlington](https://standardebooks.org/ebooks/apuleius/the-golden-ass/william-adlington)
- [Omega, by Camille Flammarion. Translated by J. B. Walker](https://standardebooks.org/ebooks/camille-flammarion/omega/j-b-walker)
- [The Conjure Woman, by Charles W. Chesnutt](https://standardebooks.org/ebooks/charles-w-chesnutt/the-conjure-woman)
- [Villette, by Charlotte Brontë](https://standardebooks.org/ebooks/charlotte-bronte/villette)
- [The Lerouge Case, by Émile Gaboriau. Translated by Vizetelly and Company](https://standardebooks.org/ebooks/emile-gaboriau/the-lerouge-case/vizetelly-and-company)
- [Short Fiction by Ernest Hemingway](https://standardebooks.org/ebooks/ernest-hemingway/short-fiction)

That's just from my alpha-sort list of the corpus, by first names/initials, from A → E. I haven't done a complete survey....

**Comment by acabal** [comment]
I think most of those are dark just as matter of art style. If any should be tweaked, *maybe* Villette and Golden Ass.

**Comment by dajare** [comment]
Okay - thanks for reviewing this, Alex. I'll take *Villette* and *Golden Ass* as "benchmarks" of sorts, and do these tweaks as time permits.

**Pull request merged**
